# Generated by Django 3.2.20 on 2023-08-28 17:35

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=blog.models.CustomDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=blog.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
